export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'


